### ISSUE TITLE
How to switch dark/light mode?

### ISSUE THREAD

**Issue by mikanIchinose** [yusukebe/gh-markdown-preview#12]
My preview is always dark mode like this.
<img width="500" alt="Screen Shot 2021-12-03 at 13 56 00" src="https://user-images.githubusercontent.com/29175998/144547629-76e01264-87d2-41e4-8148-e50ec6b09530.png">

Is there a way to switch light mode like your README?
<img width="500" alt="Screen Shot 2021-12-03 at 13 56 00" src="https://user-images.githubusercontent.com/10682/138411417-dd12a831-bacc-4b05-a33d-47d3f6b45483.png">

**Comment by yusukebe** [comment]
Hey @mikanIchinose!

I've implemented "force dark or light mode" option with `--dark-mode` or `--light-mode`. By default, following system settings.

**Comment by mikanIchinose** [comment]
I confirmed to be in light mode.
Thank you so much 👍🏻
