### ISSUE TITLE
does not support latex/mathjax

### ISSUE THREAD

**Issue by nitr7gen** [yusukebe/gh-markdown-preview#37]
[github supports mathsjax/latex](https://github.blog/2022-05-19-math-support-in-markdown/) 

but 

gh-markdown-preview extension does not

gh-markdown-preview extension:
![image](https://user-images.githubusercontent.com/115389864/198823053-a386a2ed-360c-4940-9da3-44b702e4c466.png)

github.com :
![image](https://user-images.githubusercontent.com/115389864/198823090-99624652-4e2e-4fb4-b29a-972fb5e9d5ef.png)

**Comment by yusukebe** [comment]
Hi @nitr7gen !

The new version "v1.4.0" supports Math. Please upgrade and try it!
