### ISSUE TITLE
Allow an option to render `gfm` markdown

### ISSUE THREAD

**Issue by knutwalker** [yusukebe/gh-markdown-preview#50]
In order to render GitHub extensions like [Alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) you need to set the [`mode` option to `gfm`](https://docs.github.com/en/rest/markdown/markdown?apiVersion=2022-11-28#render-a-markdown-document). Right now, there doesn't seem to be any way to trigger that: https://github.com/yusukebe/gh-markdown-preview/blob/e541afb6202b39f85ae1376649df88464e38c874/cmd/app.go#L47

Would it make sense to add a flag to switch to `gfm`, or maybe always set this mode in the API call?

**Comment by anurag-roy** [comment]
I agree! Since the aim of this plugin is to replicate the markdown rendering of GitHub.com, shouldn't we always have the `gfm` flag on?

What are your views on this? @yusukebe

**Comment by yusukebe** [comment]
Thanks to @anurag-roy , this issue has been fixed.
