### ISSUE TITLE
Alerts not Rendered as expected in Native Github Webpage

### ISSUE THREAD

**Issue by SidonTheTroll** [yusukebe/gh-markdown-preview#51]
Alerts aren't rendered in localhost of the markdown file. 

So a quick backstory, I was doing my chemistry work and wanted to use **Alerts** as a means of writing questions and rendered the file using the extension, i.e., `gh markdown-preview ./Chemistry/hydrocarbons.md`. Haven't used any tags (as seen in the screenshot below) because its the first file I opened using this extension. Would continue to use it daily if this problem is fixed. 

> [!TIP]
> Right click and open the image to view the actual quality picture.

# File as rendered by Github Webpage and the code written
|<center> <img src="https://github.com/yusukebe/gh-markdown-preview/assets/70560640/cf22182d-a091-46fe-8dd8-56e223019fab"> | <center> <img align=right src="https://github.com/yusukebe/gh-markdown-preview/assets/70560640/6f96544f-5ddf-4832-981f-815a940671f0" >| 
|-|-|

# Code rendered in `localhost` with the Extension
<img src="https://github.com/yusukebe/gh-markdown-preview/assets/70560640/89a62db9-a824-4fac-909e-920ab12286dc"> 

For assurance, check the tabs to verify the files opened by Firefox.

--- 

Btw, don't mind the unprofessional writing in this issue, I'm new to writing issues. 
Nonetheless, the output is in the terminal screenshot. 
If you missed that, go to the link of the file to open a higher quality picture.

**Comment by yusukebe** [comment]
Fixed
